version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env 
    volumes:
      - api_volume:/app
      - api_images:/app/images
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge

volumes:
  api_volume:
    driver: local
  api_images:
