version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env 
    volumes:
      - .:/app
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
