name: FastAPI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
        echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo SMTP_SERVER=${{ secrets.SMTP_SERVER }} >> .env
        echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
        echo SMTP_USER=${{ secrets.SMTP_USER }} >> .env
        echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env
        echo EMAILS_FROM_EMAIL=${{ secrets.EMAILS_FROM_EMAIL }} >> .env
        echo EMAILS_FROM_NAME=${{ secrets.EMAILS_FROM_NAME }} >> .env
        echo PROD=${{ secrets.PROD }} >> .env
        echo BASE_URL=${{ secrets.BASE_URL }} >> .env

    - name: Build and run Docker Compose
      run: |
        docker-compose down   # Stop any running containers
        docker-compose up -d --build  # Build and restart the containers
