name: FastAPI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Create .env file
      run: |
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
        echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo SMTP_SERVER=${{ secrets.SMTP_SERVER }} >> .env
        echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
        echo SMTP_USER=${{ secrets.SMTP_USER }} >> .env
        echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env
        echo EMAILS_FROM_EMAIL=${{ secrets.EMAILS_FROM_EMAIL }} >> .env
        echo EMAILS_FROM_NAME=${{ secrets.EMAILS_FROM_NAME }} >> .env

    - name: Deploy
      run: |
        # Stop and remove any existing containers and networks
        pm2 restart "poetry run uvicorn backend.main:create_app --host 0.0.0.0 --port 9090" --name fastapi
